### PR TITLE
Added totalGraph, convertUnits, includeGraphs, removed need for CSS and corrected handling of width and height.

### PR DESCRIPTION
**Pull request by hervidero**
Corrected measurements from kW to kWh for all charts except day. (More notes in the comments/commit log).
Added a total graph.
Added a convertUnits option to calculate kWH to MWh.

### CODE REVIEW

**Comment by hervidero** [comment]
Note: if you also update the version number in the package.json (and README.md), users will be notified of the update if they have notifications on..

**Comment by hervidero** [comment]
includeGraphs works!
The code needs some cleaning. Might want to put some of the recurring code into a function.

**Comment by hervidero** [comment]
With that lastest commit, I restricted the startup and update functions to only fetch and update the selected graphs/data (not always fetch all datastreams)

**Comment by hervidero** [comment]
Updated package.json to version 1.1.0, but the code still needs a bit of cleanup.

**Review by linuxtuxie — APPROVED** [review]
Again a great job Hervidero!

**Review by linuxtuxie — APPROVED** [review]

**Pull request merged**
